Port 2001
UsePAM no
PermitRootLogin prohibit-password
GSSAPIAuthentication no
KerberosAuthentication no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PasswordAuthentication no
#PubkeyAcceptedAlgorithms +ssh-rsa,ssh-dss
PubkeyAcceptedKeyTypes ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
